format = """
$python\
$username\
$hostname\
$directory\
$character"""

right_format = """
$cmd_duration\
$kubernetes\
$git_branch\
$git_commit\
$git_state\
$git_status"""

[git_branch]
symbol = " "
style = "purple"

[git_commit]
tag_symbol = '  '

[git_status]
style = "bold #555555"
up_to_date = '[✓](green)'
modified = '[!](yellow)'
stashed = '[⚑](cyan)'
staged = '[+](green)'
untracked = '[?](red)'
ahead = '[⇡](green)'
behind = '[⇣](red)'
diverged = '[⇕](orange)'

[directory]
style = "blue"
truncate_to_repo = true
truncation_length = 2

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
format = '(\($virtualenv\)) '

[kubernetes]
disabled = true
